name: Veszee_env
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - astropy=4.0.2
  - blas=1.0
  - ca-certificates=2021.10.8
  - certifi=2021.5.30
  - dbus=1.13.18
  - dill=0.3.4
  - expat=2.4.1
  - fftw=3.3.8
  - fontconfig
  - freetype=2.11.0
  - galario=1.2.2
  - glib=2.69.1
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - icu=58.2
  - intel-openmp=2021.4.0
  - jpeg=9d
  - lcms2=2.12
  - ld_impl_linux-64=2.35.1
  - libffi=3.3
  - libgcc-ng=9.3.0
  - libgfortran=3.0.0
  - libgfortran-ng=7.5.0
  - libgfortran4=7.5.0
  - libgomp=9.3.0
  - libpng=1.6.37
  - libstdcxx-ng=9.3.0
  - libtiff=4.2.0
  - libuuid=1.0.3
  - libwebp-base=1.2.0
  - libxcb=1.14
  - libxml2=2.9.12
  - lz4-c=1.9.3
  - matplotlib-base=3.3.4
  - mkl=2020.2
  - mkl-service=2.3.0
  - mkl_fft=1.3.0
  - mkl_random=1.1.1
  - ncurses=6.3
  - numpy-base=1.19.2
  - olefile=0.46
  - openjpeg=2.4.0
  - openssl=1.1.1l
  - pcre=8.45
  - pillow=8.3.1
  - pip=21.2.2
  - pyqt=5.9.2
  - python=3.6.13
  - python_abi=3.6
  - qt=5.9.7
  - readline=8.1
  - setuptools=58.0.4
  - sip=4.19.8
  - sqlite=3.36.0
  - tk=8.6.11
  - tornado=6.1
  - wheel=0.37.0
  - xz=5.2.5
  - zlib=1.2.11
  - zstd=1.4.9
  - pip:
    - anyio==3.5.0
    - argon2-cffi==21.3.0
    - argon2-cffi-bindings==21.2.0
    - async-generator==1.10
    - attrs==21.4.0
    - babel==2.9.1
    - backcall==0.2.0
    - bleach==4.1.0
    - cffi==1.15.0
    - charset-normalizer==2.0.12
    - contextvars==2.4
    - corner==2.2.1
    - cycler==0.10.0
    - dataclasses==0.8
    - decorator==5.1.1
    - defusedxml==0.7.1
    - dynesty==1.1
    - entrypoints==0.4
    - idna==3.3
    - immutables==0.16
    - importlib-metadata==4.8.3
    - importlib-resources==5.4.0
    - ipykernel==5.5.6
    - ipython==7.16.3
    - ipython-genutils==0.2.0
    - jedi==0.17.2
    - jinja2==3.0.3
    - json5==0.9.6
    - jsonschema==3.2.0
    - jupyter-client==7.1.2
    - jupyter-core==4.9.2
    - jupyter-server==1.13.1
    - jupyterlab==3.2.9
    - jupyterlab-pygments==0.1.2
    - jupyterlab-server==2.10.3
    - kiwisolver==1.2.0
    - markupsafe==2.0.1
    - matplotlib==3.2.1
    - mistune==0.8.4
    - nbclassic==0.3.5
    - nbclient==0.5.9
    - nbconvert==6.0.7
    - nbformat==5.1.3
    - nest-asyncio==1.5.4
    - notebook==6.4.8
    - numpy==1.18.4
    - packaging==21.3
    - pandocfilters==1.5.0
    - parso==0.7.1
    - pexpect==4.8.0
    - pickle5==0.0.12
    - pickleshare==0.7.5
    - prometheus-client==0.13.1
    - prompt-toolkit==3.0.28
    - ptyprocess==0.7.0
    - pycparser==2.21
    - pygments==2.11.2
    - pyparsing==2.4.7
    - pyrsistent==0.18.0
    - python-dateutil==2.8.1
    - pytz==2021.3
    - pyzmq==22.3.0
    - requests==2.27.1
    - scipy==1.4.1
    - send2trash==1.8.0
    - six==1.15.0
    - sniffio==1.2.0
    - terminado==0.12.1
    - testpath==0.6.0
    - tqdm==4.63.0
    - traitlets==4.3.3
    - typing-extensions==4.1.1
    - urllib3==1.26.8
    - wcwidth==0.2.5
    - webencodings==0.5.1
    - websocket-client==1.3.1
    - zipp==3.6.0
    - -e .
